my_donation_data/urls.py
from django.urls import include, path
from my_donation_data import views

app_name = 'my_donation_data'
 
urlpatterns = [
	path('',views.home,name='home'),
	path('ourwork',views.ourwork,name='ourwork'),
	path('donateus',views.donateus,name='donateus'),
	path('donation_form_submit',views.donation_form_submit,name='donation_form_submit'),
]

my_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('my_donation_data.urls')),
]

my_donation_data/models.py
from django.db import models

# Create your models here.
#Donation Form Model
class DonationForm(models.Model):
    #Total Fields : 5
    #------Donation form Table Fields------

    #This field store Full Name 
    full_name = models.CharField(max_length=300,blank=True)
    #This field store Email ID
    email_id = models.CharField(max_length=300,blank=True)
    #This field store Contact Number 
    contact_number = models.CharField(max_length=300,blank=True)
    #This field store Donation Amount 
    donation = models.CharField(max_length=300,blank=True)
    #This field store Message 
    message = models.TextField(max_length=3000,blank=True)
    #This field store Date & Time at which form is submitted
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.pk) #Return Primary Key

    class Meta:
        verbose_name_plural = "Donation Form Data"
        verbose_name = "Donation Form"

my_donation_data/views.py
from django.shortcuts import render
from my_donation_data.models import DonationForm
from django.shortcuts import render,HttpResponseRedirect,HttpResponse
from django.urls import reverse

# Create your views here.
def home(request):
	return render(request,'my_donation_data/home.html')

def ourwork(request):
	return render(request,'my_donation_data/ourwork.html')

def donateus(request):
	return render(request,'my_donation_data/donateus.html')

def donation_form_submit(request):
    if request.method == "POST":
        full_name = request.POST['full_name']
        email_id = request.POST['email_id']
        contact_number = request.POST['contact_number']
        donation = request.POST['donation']
        message = request.POST['message']
        DonationForm.objects.create(full_name=full_name,
                                   email_id=email_id,
                                   contact_number=contact_number,
                                   donation=donation,
                                   message=message
                                   )
    return HttpResponseRedirect(reverse('my_donation_data:donateus'))

my_donation_data/templates/my_donation_data/base.html
<!DOCTYPE html>
<html>
{% load static %}
<head>
    <title>Non-Profit Charity Application</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel='stylesheet' href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.1.0-4/css/all.css">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    {% block stylesheets %}
    {% endblock stylesheets %}  
    
    {% block headscript %}
    {% endblock headscript %}
    <style>
        body {
            background-color: #E1FFC2;
        }
    </style>
</head>
<body>
    <div>
        <nav class="navbar navbar-expand-lg navbar-dark bg-success fixed-top">
            <a class="navbar-brand"><img src="{% static 'my_donation_app/img/logo.jpg' %}" class="rounded" alt="Non-Profit Charity Logo" height="50px"><b> High Fives Foundation </b></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
                <ul class="navbar-nav ml-auto ">
                    <li class="nav-item ">
                        <a class="nav-link" style="color: #fff" href="{% url 'my_donation_data:home' %}">About</a>
                    </li> 
                    <li class="nav-item ">
                        <a class="nav-link" style="color: #fff" href="{% url 'my_donation_data:ourwork' %}">Our Work</a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link" style="color: #fff" href="{% url 'my_donation_data:donateus' %}">Donate</a>
                    </li>
                </ul>
            </div>
        </nav>
    </div>
    {% block content %}
    {% endblock %}
    
    {% block script %}
    {% endblock %}
</body>
</html>

my_donation_data/templates/my_donation_data/donateus.html
{% extends 'my_donation_data/base.html' %}
{% load static %}

{% block stylesheets %}
<style>
    body{
      color: #251f44;
    }

    .box {
        margin-top: 6rem;
    }

    ul {
        position: relative;
        right: 0;
    }

    .row input {
        margin-bottom: 2rem;
        border: 0;
        box-shadow: 0;
         !importatnt
    }

    .row textarea {
        margin-bottom: 2rem;
        border: 0;
    }

    .box h1 {
        margin-bottom: 5rem;
    }

    .icons {
        margin-top: 3rem;
    }

    .copy {
        margin-top: 1rem;
    }

    .icons a {
        color: #ccc;
        margin: 1rem;
    }

    .icons a:hover {
        color: #000;
    }
</style>

{% endblock stylesheets %}


{% block headscript %}
{% endblock headscript %}


{% block content %}
<div class="container">

    <div class="box shadow-lg p-3 mb-5 bg-white rounded">
        <div>
            <center>
                <h1 style="color: #a2de96">DONATE NOW</h1>
            </center>
        </div>
        <div class=" container">
            <form method="POST" action="{% url 'my_donation_data:donation_form_submit' %}">
                {% csrf_token %}
                <div class="row">
                    <div class="form-group col-sm-4">
                        <input type="text" id="full_name" name="full_name" class="form-control form-control-lg border-bottom border-dark shadow-none" placeholder="Name">
                    </div>
                    <div class="form-group  col-sm-4">
                        <input type="text" id="email_id" name="email_id" class="form-control form-control-lg border-bottom border-dark shadow-none" placeholder="Email">
                    </div>
                    <div class="form-group col-sm-4">
                        <input type="text" id="contact_number" name="contact_number" class="form-control form-control-lg border-bottom border-dark shadow-none" placeholder="Contact">
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-12">
                        <input type="text" id="donation" name="donation" class="form-control form-control-lg border-bottom border-dark shadow-none" placeholder="Donation">
                    </div>
                    <div class="col-md-12">
                        <textarea id="message" name="message" class="form-control form-control-lg border-bottom border-dark shadow-none" rows="5" placeholder="Your Message"></textarea>
                    </div>
                    <div class="col-md-12">
                        <center> <button type="submit" class="btn-success btn btn-lg">Submit</button></center>
                    </div>

                </div>
            </form>
        </div>
        <div class="container">
            <div class="copy">
                <center>
                    <h6>&copy;2020 High Five Foundation</h6>
                </center>

            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block script %}
{% endblock %}

my_donation_data/templates/my_donation_data/home.html
{% extends 'my_donation_data/base.html' %}
{% load static %}
{% block stylesheets %}
<style>
  body {
  padding-top: 3rem;
  padding-bottom: 3rem;
  color: #251f44;
}


/* CUSTOMIZE THE CAROUSEL
-------------------------------------------------- */

/* Carousel base class */
.carousel {
  margin-bottom: 4rem;
}
/* Since positioning the image, we need to help out the caption */
.carousel-caption {
  bottom: 3rem;
  z-index: 10;
}

/* Declare heights because of positioning of img element */
.carousel-item {
  height: 32rem;
  background-color: #777;
}
.carousel-item > img {
  position: absolute;
  top: 0;
  left: 0;
  min-width: 100%;
  height: 32rem;
}


/* MARKETING CONTENT
-------------------------------------------------- */

/* Center align the text within the three columns below the carousel */
.marketing .col-lg-4 {
  margin-bottom: 1.5rem;
  text-align: center;
}
.marketing h2 {
  font-weight: 400;
}
.marketing .col-lg-4 p {
  margin-right: .75rem;
  margin-left: .75rem;
}


/* Featurettes
------------------------- */

.featurette-divider {
  margin: 5rem 0; /* Space out the Bootstrap <hr> more */
}

/* Thin out the marketing headings */
.featurette-heading {
  font-weight: 300;
  line-height: 1;
  letter-spacing: -.05rem;
}


/* RESPONSIVE CSS
-------------------------------------------------- */

@media (min-width: 40em) {
  /* Bump up size of carousel content */
  .carousel-caption p {
    margin-bottom: 1.25rem;
    font-size: 1.25rem;
    line-height: 1.4;
  }

  .featurette-heading {
    font-size: 50px;
  }
}

@media (min-width: 62em) {
  .featurette-heading {
    margin-top: 7rem;
  }
}
</style>
{% endblock stylesheets %}
    
{% block headscript %}
{% endblock headscript %}

{% block content %}
    <main role="main">

      <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
          <li data-target="#myCarousel" data-slide-to="1"></li>
          <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img class="first-slide" src="{% static 'my_donation_app/img/slide1.jpg' %}" alt="First slide">
            <div class="container">
              <div class="carousel-caption text-left">
                <h1>“No one has ever become poor by giving.”</h1>
                <p>― Anne Frank</p>
              </div>
            </div>
          </div>
          <div class="carousel-item">
            <img class="second-slide" src="{% static 'my_donation_app/img/slide4.jpg' %}" alt="Second slide">
            <div class="container">
              <div class="carousel-caption" style="color: #000000;">
                <h1>“It's not how much we give but how much love we put into giving.”</h1>
                <p>― Mother Theresa</p>
              </div>
            </div>
          </div>
          <div class="carousel-item">
            <img class="third-slide" src="{% static 'my_donation_app/img/slide3.jpg' %}" alt="Third slide">
            <div class="container">
              <div class="carousel-caption text-right">
                <h1>“There is no exercise better for the heart than reaching down and lifting people up.”</h1>
                <p>― John Holmes</p>
              </div>
            </div>
          </div>
        </div>
        <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>


      <!-- Marketing messaging and featurettes
      ================================================== -->
      <!-- Wrap the rest of the page in another container to center all the content. -->

      <div class="container marketing">

        <!-- Three columns of text below the carousel -->
        <div class="row">
          <div class="col-lg-4">
            <img class="rounded-circle" src="{% static 'my_donation_app/img/donate1.jpg' %}" alt="Generic placeholder image" width="140" height="140">
            <h2>Importance of Hand Sanitizers</h2>
            <p>Hand Sanitizers will be provided to the families and workers to protect their themselves for spreading coronavirus.</p>
          </div><!-- /.col-lg-4 -->
          <div class="col-lg-4">
            <img class="rounded-circle" src="{% static 'my_donation_app/img/donate2.jpg' %}" alt="Generic placeholder image" width="140" height="140">
            <h2>Funds for Patients in need of Treatments</h2>
            <p>Due to the increase in the number of Covid-19 patients, they are not able to pay for high price treatments. So, your donations will help themselves get treated.
          </div><!-- /.col-lg-4 -->
          <div class="col-lg-4">
            <img class="rounded-circle" src="{% static 'my_donation_app/img/donate3.jpg' %}" alt="Generic placeholder image" width="140" height="140">
            <h2>Food for Families and Workers</h2>
            <p>Many of these families are suffering with starvation. We are feeding hungry homeless and daily workers at their locations. We identified such families and helping them by donating groceries kit consist of Rice, Dal, Atta, Oil, Soaps, Tamarind, Onion.</p>
          </div><!-- /.col-lg-4 -->
        </div><!-- /.row -->


        <!-- START THE FEATURETTES -->

        <hr class="featurette-divider">

        <div class="row featurette">
          <div class="col-md-7">
            <h2 class="featurette-heading">Coronavirus Relief Fund</h2>
            <p class="lead">The COVID-19 pandemic marks an unprecedented time in modern history that will require the best of humanity to overcome. Your donation to this fund will help stop COVID-19's spread and protect us all.</p>
          </div>
          <div class="col-md-5">
            <img class="featurette-image img-fluid mx-auto" src="{% static 'my_donation_app/img/heading1.jpg' %}" alt="Generic placeholder image">
          </div>
        </div>

        <hr class="featurette-divider">

        <div class="row featurette">
          <div class="col-md-7 order-md-2">
            <h2 class="featurette-heading">Donate for DailyWage Workers during COVID-19 India</h2>
            <p class="lead">Sudden Lock down & Pandemic COVID-19 the daily wage earners and migrant workers lost their income. Many of these families are suffering with starvation. We identified such families and helping them by donating groceries kit consist of Rice, Dal, Ata, Oil, Soaps, Hand wash, Tamarind, Onion, Masks, Sanitizers.</p>
          </div>
          <div class="col-md-5 order-md-1">
            <img class="featurette-image img-fluid mx-auto" src="{% static 'my_donation_app/img/heading2.jpg' %}" alt="Generic placeholder image">
          </div>
        </div>

        <hr class="featurette-divider">

        <div class="row featurette">
          <div class="col-md-7">
            <h2 class="featurette-heading">COVID19: Education & Food for Palestinian Children</h2>
            <p class="lead">Refugee children and their families in Nablus, Palestine, have been hit hard by the impact of COVID-19. Most families have lost their only source of income and aren't able to put food on the table. We are delivering food, medicine and basic supplies to as many at-risk families as possible, and have transitioned to an online education curriculum to provide quality, distance learning resources that refugee children can access from home.</p>
          </div>
          <div class="col-md-5">
            <img class="featurette-image img-fluid mx-auto" src="{% static 'my_donation_app/img/heading3.jpg' %}" alt="Generic placeholder image">
          </div>
        </div>

        <hr class="featurette-divider">

        <!-- /END THE FEATURETTES -->

      </div><!-- /.container -->


      <!-- FOOTER -->
      <footer class="container">
        <p>&copy; 2020-2021 High Fives Foundation &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
      </footer>
    </main>
{% endblock %}
 
{% block script %}
{% endblock %}

my_donation_data/templates/my_donation_data/ourwork.html
{% extends 'my_donation_data/base.html' %}
{% load static %}
{% block stylesheets %}
<style>

body{
  color: #251f44;
}

:root {
  --jumbotron-padding-y: 3rem;
}

.jumbotron {
  padding-top: var(--jumbotron-padding-y);
  padding-bottom: var(--jumbotron-padding-y);
  margin-bottom: 0;
  background-color: #fff;
}
@media (min-width: 768px) {
  .jumbotron {
    padding-top: calc(var(--jumbotron-padding-y) * 2);
    padding-bottom: calc(var(--jumbotron-padding-y) * 2);
  }
}

.jumbotron .container {
  max-width: 40rem;
}

.box-shadow { box-shadow: 0 .25rem .75rem rgba(0, 0, 0, .05); }

</style>
{% endblock stylesheets %}
    
{% block headscript %}
{% endblock headscript %}

{% block content %}
    <main role="main">

      <section class="jumbotron text-center" style="background-color: #E1FFC2;">
          <h1 class="display-4">Our Work</h1>
          <h3 class="text-center">The world is facing an unprecedented challenge with communities and economies everywhere affected by the growing COVID-19 pandemic. The world is coming together to combat the COVID-19 pandemic bringing governments, organizations from across industries and sectors and individuals together to help respond to this global outbreak. Our Foundation will aim at raising funds for the families who are facing the economic crisis who are unable to pay for basic necessities including rent, utilities, and food. For the following 2 months, High Five Foundation has done a set of charity events for the Families and Workers.</h3>
      </section>
      <div class="album py-5" style="background-color: #E1FFC2;">
        <div class="container">
          <div class="row">
            <div class="col-md-4">
              <div class="card mb-4 box-shadow">
                <img class="card-img-top" src="{% static 'my_donation_app/img/1.jpg' %}" alt="Card image cap">
                <div class="card-body">
                  <p class="card-text">Coronavirus Relief for NYC's Children and Families</p>
                  <div class="d-flex justify-content-between align-items-center">
                    <small class="text-muted">12 days ago</small>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-4">
              <div class="card mb-4 box-shadow">
                <img class="card-img-top" src="{% static 'my_donation_app/img/2.jpg' %}" alt="Card image cap">
                <div class="card-body">
                  <p class="card-text">Feed migrant workers & daily wagers in India</p>
                  <div class="d-flex justify-content-between align-items-center">
                    <small class="text-muted">3 days ago</small>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-4">
              <div class="card mb-4 box-shadow">
                <img class="card-img-top" src="{% static 'my_donation_app/img/3.jpg' %}" alt="Card image cap">
                <div class="card-body">
                  <p class="card-text">Help a Child: Provide Access to Water in Nigeria</p>
                  <div class="d-flex justify-content-between align-items-center">
                    <small class="text-muted">25 days ago</small>
                  </div>
                </div>
              </div>
            </div>

            <div class="col-md-4">
              <div class="card mb-4 box-shadow">
                <img class="card-img-top" src="{% static 'my_donation_app/img/4.jpg' %}" alt="Card image cap">
                <div class="card-body">
                  <p class="card-text">COVID-19 Aid for Education in Afghanistan</p>
                  <div class="d-flex justify-content-between align-items-center">
                    <small class="text-muted">15 days ago</small>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-4">
              <div class="card mb-4 box-shadow">
                <img class="card-img-top" src="{% static 'my_donation_app/img/5.jpg' %}" alt="Card image cap">
                <div class="card-body">
                  <p class="card-text">Coronavirus Relief Support for Bangladesh</p>
                  <div class="d-flex justify-content-between align-items-center">
                    <small class="text-muted">9 days ago</small>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-4">
              <div class="card mb-4 box-shadow">
                <img class="card-img-top" src="{% static 'my_donation_app/img/6.jpg' %}" alt="Card image cap">
                <div class="card-body">
                  <p class="card-text">Food & fruit for 1,000 children in Latin America</p>
                  <div class="d-flex justify-content-between align-items-center">
                    <small class="text-muted">17 days ago</small>
                  </div>
                </div>
              </div>
            </div>

            <div class="col-md-4">
              <div class="card mb-4 box-shadow">
                <img class="card-img-top" src="{% static 'my_donation_app/img/7.jpg' %}" alt="Card image cap">
                <div class="card-body">
                  <p class="card-text">Food & fruit for 1,000 children in Latin America</p>
                  <div class="d-flex justify-content-between align-items-center">
                    <small class="text-muted">10 days ago</small>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-4">
              <div class="card mb-4 box-shadow">
                <img class="card-img-top" src="{% static 'my_donation_app/img/8.png' %}" alt="Card image cap">
                <div class="card-body">
                  <p class="card-text">Coronavirus Relief Aid Distribution</p>
                  <div class="d-flex justify-content-between align-items-center">
                    <small class="text-muted">1 month 3 days ago</small>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-4">
              <div class="card mb-4 box-shadow">
                <img class="card-img-top" src="{% static 'my_donation_app/img/9.jpg' %}" alt="Card image cap">
                <div class="card-body">
                  <p class="card-text">Nepal Emergency COVID-19 fund</p>
                  <div class="d-flex justify-content-between align-items-center">
                    <small class="text-muted">2 months ago</small>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

    </main>
{% endblock %}
 
{% block script %}
{% endblock %}